# Generated by Django 5.2 on 2026-03-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos', models.CharField(max_length=100, verbose_name='apellidos')),
                ('nombre_tutor1', models.CharField(max_length=100, verbose_name='tutor 1')),
                ('nombre_tutor2', models.CharField(blank=True, max_length=100, verbose_name='tutor 2')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('telefono2', models.CharField(blank=True, max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('localidad', models.CharField(blank=True, max_length=100)),
                ('cp', models.CharField(blank=True, max_length=10, verbose_name='C.P.')),
                ('notas', models.TextField(blank=True)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'familia',
                'verbose_name_plural': 'familias',
                'ordering': ['apellidos'],
            },
        ),
    ]
